apiVersion: v2
name: arc
description: High-Performance Time-Series Data Warehouse - One database for metrics, logs, traces, and events
type: application
version: 25.11.1
appVersion: "25.11.1"
keywords:
  - database
  - timeseries
  - observability
  - duckdb
  - analytics
home: https://github.com/Basekick-Labs/arc
sources:
  - https://github.com/Basekick-Labs/arc
maintainers:
  - name: Basekick Labs
    email: contact@basekick.com
